AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda function that executes price optimizer

Globals:
  Function:
    Timeout: 180
    MemorySize: 128

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0/8 * ? * * *) #the function is triggered every 8 minutes
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./data_producer
      DockerTag: python3.9-v1
